# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Main
                                 A QGIS plugin
 Scheletro di prova per il plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-14
        copyright            : (C) 2025 by Martin Pedron
        email                : pedronmartin64@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Main class from file Main.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GreenRatingAlgorithm import Main
    return Main(iface)
